apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: admin
  ports:
  - protocol: TCP
    port: {{ .Values.admin.port }}
    targetPort: {{ .Values.admin.port }}
    nodePort: 30090
  type: NodePort