apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: {{ .Values.adminServer.repository }}:{{ .Values.adminServer.tag }}
        ports:
        - containerPort: {{ .Values.adminServer.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888