apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: {{ .Values.adminServer.repository }}:{{ .Values.adminServer.tag }}
        ports:
        - containerPort: {{ .Values.adminServer.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888
        - name: SPRING_LOGGING_FILE_NAME
          value: ""
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: admin-server
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
        - name: EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS
          value: "10"
        - name: EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS
          value: "60"
        - name: EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS
          value: "60"
        - name: SPRING_BOOT_ADMIN_CLIENT_PERIOD
          value: "30000"