apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: {{ .Values.api-gateway.port }}
    targetPort: {{ .Values.api-gateway.port }}
    nodePort: 30110
  type: NodePort