apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: {{ .Values.configServer.repository }}:{{ .Values.configServer.tag }}
        ports:
        - containerPort: {{ .Values.configServer.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888