apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: {{ .Values.configServer.port }}
    targetPort: {{ .Values.configServer.port }}
    nodePort: 30120
  type: NodePort