apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: {{ .Values.discovery-server.repository }}:{{ .Values.discovery-server.tag }}
        ports:
        - containerPort: {{ .Values.discovery-server.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker