apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: {{ .Values.discoveryServer.repository }}:{{ .Values.discoveryServer.tag }}
        ports:
        - containerPort: {{ .Values.discoveryServer.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888