apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: discovery-server
  ports:
  - protocol: TCP
    port: {{ .Values.discovery-server.port }}
    targetPort: {{ .Values.discovery-server.port }}
    nodePort: 30080
  type: NodePort