apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: {{ .Values.eureka.port }}
    targetPort: {{ .Values.eureka.port }}
    nodePort: 30080
  type: NodePort