apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: {{ .Values.gateway.port }}
    targetPort: {{ .Values.gateway.port }}
    nodePort: {{ add .Values.gateway.port 20000 }}
  type: NodePort