apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: genai-service
  ports:
  - protocol: TCP
    port: {{ .Values.genai-service.port }}
    targetPort: {{ .Values.genai-service.port }}
    nodePort: 30140
  type: NodePort