apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: {{ .Values.genai-service.repository }}:{{ .Values.genai-service.tag }}
        ports:
        - containerPort: {{ .Values.genai-service.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker