apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai
  template:
    metadata:
      labels:
        app: genai
    spec:
      containers:
      - name: genai
        image: {{ .Values.genai.repository }}:{{ .Values.genai.tag }}
        ports:
        - containerPort: {{ .Values.genai.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker