apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server
        image: {{ .Values.tracingServer.repository }}:{{ .Values.tracingServer.tag }}
        ports:
        - containerPort: {{ .Values.tracingServer.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        readinessProbe:
          httpGet:
            path: /api/v2/services
            port: {{ .Values.tracingServer.port }}
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /api/v2/services
            port: {{ .Values.tracingServer.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2