apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server
        image: {{ .Values.tracingServer.repository }}:{{ .Values.tracingServer.tag }}
        ports:
        - containerPort: {{ .Values.tracingServer.port }}
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        readinessProbe:
          httpGet:
            path: /api/v2/services
            port: {{ .Values.tracingServer.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /api/v2/services
            port: {{ .Values.tracingServer.port }}
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 5