apiVersion: v1
kind: Service
metadata:
  name: vets
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: vets
  ports:
  - protocol: TCP
    port: {{ .Values.vets.port }}
    targetPort: {{ .Values.vets.port }}
    nodePort: 30150
  type: NodePort