apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: vets-service
  ports:
  - protocol: TCP
    port: {{ .Values.vets-service.port }}
    targetPort: {{ .Values.vets-service.port }}
    nodePort: 30150
  type: NodePort