apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: visits-service
  ports:
  - protocol: TCP
    port: {{ .Values.visits-service.port }}
    targetPort: {{ .Values.visits-service.port }}
    nodePort: 30160
  type: NodePort