apiVersion: v1
kind: Service
metadata:
  name: visits
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: visits
  ports:
  - protocol: TCP
    port: {{ .Values.visits.port }}
    targetPort: {{ .Values.visits.port }}
    nodePort: {{ add .Values.visits.port 20000 }}
  type: NodePort