apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: {{ .Values.visitsService.repository }}:{{ .Values.visitsService.tag }}
        ports:
        - containerPort: {{ .Values.visitsService.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888