apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: zipkin
  ports:
  - protocol: TCP
    port: {{ .Values.zipkin.port }}
    targetPort: {{ .Values.zipkin.port }}
    nodePort: {{ add .Values.zipkin.port 20000 }}
  type: NodePort